limit.type: redis
spring:
    # DataSource Config
#    datasource:
##        url: jdbc:sqlserver://:1433;DatabaseName=Exchange
##        username: application_user
##        password: DEV219application_user
#
#        url: jdbc:sqlserver://:1433;DatabaseName=Exchange
#        username: qa_user
#        password: QA2qa_user
#        # 使用druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#        max-active: 30
#        initial-size: 40
#        min-idle: 20
#        max-wait: 60000
#        time-between-eviction-runs-millis: 60000
#        min-evictable-idle-time-millis: 300000
#        validation-query: SELECT 'x' FROM DUAL
#        test-while-idle: true
#        test-on-borrow: false
#        test-on-return: false
#        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#        filters: stat,wall,log4j
#        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
#
#    redis:
#        host: 172.16.5.124
#        port: 6379
#        usePool: true
#
#mybatis:
#    mapper-locations: classpath:mybatis/*.xml
#    config-location: classpath:mybatis-config.xml
#
## dubbo配置
#dubbo:
#    registry:
#        address: zookeeper://127.0.0.1:2181

server:
    port: 9100




